//go:build integration

package backup_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"filippo.io/age"
	"github.com/vyruss/pgsafe/internal/backup"
	"github.com/vyruss/pgsafe/internal/filter"
	"github.com/vyruss/pgsafe/internal/filter/pagechecksum"
	"github.com/vyruss/pgsafe/internal/pg"
	"github.com/vyruss/pgsafe/internal/pg/conn"
	"github.com/vyruss/pgsafe/internal/pg/pgtest"
	"github.com/vyruss/pgsafe/internal/storage/posix"
)

// TestRemoteParallelEndToEnd runs the full ModeRemoteParallel caller
// against a real PG 18 container: bracket.Start → ListPGData → parallel
// streaming → bracket.Stop → WAL-wait → manifest commit. Verifies the same
// post-conditions as TestCallerStrictStepOrdering — backup_manifest
// committed atomically, sidecar present, recognizable cluster files in storage.
//
// c gate.
func TestRemoteParallelEndToEnd(t *testing.T) {
	t.Parallel()
	pgInst := pgtest.StartPG18(t)
	ctx := context.Background()

	// Seed a bit of real heap so the workers stream non-trivial bytes through
	// the page-checksum validator.
	pgInst.MustExec(t, `CREATE TABLE rp_demo (id int primary key, body text)`)
	pgInst.MustExec(t, `INSERT INTO rp_demo SELECT g, repeat('x', 100) FROM generate_series(1, 200) g`)
	pgInst.MustExec(t, `CHECKPOINT`)

	pool, err := conn.Connect(ctx, pgInst.SuperDSN)
	if err != nil {
		t.Fatalf("Connect: %v", err)
	}
	defer pool.Close()

	cluster, err := pg.Open(ctx, pgInst.SuperDSN)
	if err != nil {
		t.Fatalf("pg.Open: %v", err)
	}
	defer cluster.Close()

	// POSIX storage backed by a tempdir, with WAL archive bind-mounted by pgtest.
	// Symlink <repoRoot>/wal → pgInst.WALArchive so the caller's backend
	// sees archive_command's output at the expected wal/<TLI>/<seg> key.
	root := t.TempDir()
	repoRoot := filepath.Join(root, "storage")
	if err := os.MkdirAll(repoRoot, 0o755); err != nil { //nolint:gosec
		t.Fatalf("mkdir storage: %v", err)
	}
	if err := os.Symlink(pgInst.WALArchive, filepath.Join(repoRoot, "wal")); err != nil {
		t.Fatalf("symlink wal: %v", err)
	}
	storage, err := posix.New(posix.Options{Root: repoRoot})
	if err != nil {
		t.Fatalf("posix.New: %v", err)
	}
	if err := storage.Open(ctx); err != nil {
		t.Fatalf("storage.Open: %v", err)
	}

	id, _ := age.GenerateX25519Identity()
	chain, err := filter.NewChain(filter.Options{
		Codec:      "gzip",
		Recipients: []age.Recipient{id.Recipient()},
	})
	if err != nil {
		t.Fatalf("filter.NewChain: %v", err)
	}

	res, err := backup.Run(ctx, backup.Options{
		Cluster:    cluster,
		Backend:    storage,
		Filter:     chain,
		Mode:       backup.ModeRemoteParallel,
		Server:     "demo",
		Label:      "pgsafe-rp-test",
		WALTimeout: 60 * time.Second,
		Now:        time.Now,
		RemoteParallel: backup.RemoteParallelOptions{
			Pool:             pool,
			Workers:          2,
			PGVersion:        pgInst.Version,
			PageChecksumMode: pagechecksum.ModeOff,
		},
	})
	if err != nil {
		t.Fatalf("backup.Run: %v", err)
	}
	if res.Files < 50 {
		t.Errorf("Files = %d, want at least 50 (cluster has more)", res.Files)
	}
	if res.StartLSN >= res.StopLSN {
		t.Errorf("StartLSN=%s >= StopLSN=%s", res.StartLSN, res.StopLSN)
	}

	// Locate the backup directory: <repoRoot>/<id>F.
	entries, err := os.ReadDir(repoRoot)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	var backupDir string
	for _, e := range entries {
		if e.IsDir() && strings.HasSuffix(e.Name(), "F") && e.Name() != "wal" {
			backupDir = e.Name()
			break
		}
	}
	if backupDir == "" {
		t.Fatalf("no backup directory created in %s", repoRoot)
	}

	// Manifest must exist and the .tmp must NOT (Invariant #2).
	if _, err := os.Stat(filepath.Join(repoRoot, backupDir, "backup_manifest")); err != nil {
		t.Errorf("backup_manifest missing: %v", err)
	}
	if _, err := os.Stat(filepath.Join(repoRoot, backupDir, "backup_manifest.tmp")); !os.IsNotExist(err) {
		t.Errorf("backup_manifest.tmp leaked after Commit; err=%v", err)
	}
	// Sidecar must exist.
	if _, err := os.Stat(filepath.Join(repoRoot, backupDir, "Storage-Metadata.json")); err != nil {
		t.Errorf("Storage-Metadata.json missing: %v", err)
	}
	// Recognizable cluster files.
	if _, err := os.Stat(filepath.Join(repoRoot, backupDir, "PG_VERSION")); err != nil {
		t.Errorf("PG_VERSION missing in storage: %v", err)
	}
	if _, err := os.Stat(filepath.Join(repoRoot, backupDir, "global", "pg_control")); err != nil {
		t.Errorf("global/pg_control missing in storage: %v", err)
	}
	// backup_label is generated by bracket.Stop, not present in $PGDATA.
	if _, err := os.Stat(filepath.Join(repoRoot, backupDir, "backup_label")); err != nil {
		t.Errorf("backup_label missing in storage: %v", err)
	}

	t.Logf("remote-parallel backup: id=%s files=%d bytes=%d duration=%s",
		res.BackupID, res.Files, res.Bytes, res.Duration)
}
