//go:build demo_fixture

// Package demo holds a single test, TestHoldFixture, that brings up the
// hybrid-parallel sshtest topology, ships a freshly-built pgsafe binary
// into the container, prints the operator-facing connection details to
// a sentinel file, and blocks until SIGINT/SIGTERM. It exists to back
// the asciinema demo: the demo script launches this in the background,
// reads the sentinel file, then drives `pgsafe ...` from the same shell
// against the held-open fixture.
//
// Not run by the normal test suite — gated by `-tags=demo_fixture`.
package demo

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strconv"
	"syscall"
	"testing"
	"time"

	"github.com/vyruss/pgsafe/internal/transport/sshtest"
)

func TestHoldFixture(t *testing.T) {
	topo := sshtest.StartPG18WithSSH(t)

	// Build pgsafe linux/amd64 and ship it into the container.
	binDir := t.TempDir()
	binPath := filepath.Join(binDir, "pgsafe")
	build := exec.Command("go", "build", "-o", binPath, "../../cmd/pgsafe")
	cleanEnv := make([]string, 0, len(os.Environ()))
	for _, e := range os.Environ() {
		if len(e) > 5 && (e[:5] == "GOOS=" || e[:7] == "GOARCH=") {
			continue
		}
		cleanEnv = append(cleanEnv, e)
	}
	build.Env = append([]string{"GOOS=linux", "GOARCH=amd64", "CGO_ENABLED=0"}, cleanEnv...)
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build pgsafe: %v\n%s", err, out)
	}

	const remoteBin = "/tmp/pgsafe"
	if err := scpUpload(topo, binPath, remoteBin); err != nil {
		t.Fatalf("scp upload: %v", err)
	}
	if err := chmodRemote(topo, remoteBin, "0755"); err != nil {
		t.Fatalf("chmod remote: %v", err)
	}

	// Write a small env-var dump that the demo script can `source`.
	out := os.Getenv("PGSAFE_DEMO_ENV_FILE")
	if out == "" {
		out = "/tmp/pgsafe-demo-env.sh"
	}
	body := fmt.Sprintf(`# generated by TestHoldFixture
export PGSAFE_DEMO_SUPER_DSN=%q
export PGSAFE_DEMO_DSN=%q
export PGSAFE_DEMO_SSH_HOST=%q
export PGSAFE_DEMO_SSH_PORT=%d
export PGSAFE_DEMO_SSH_USER=%q
export PGSAFE_DEMO_SSH_KEY=%q
export PGSAFE_DEMO_SSH_KNOWN_HOSTS=%q
export PGSAFE_DEMO_SSH_TARGET=%q
export PGSAFE_DEMO_HOST_STORAGE=%q
export PGSAFE_DEMO_CONTAINER_STORAGE=%q
export PGSAFE_DEMO_REMOTE_BIN=%q
export PGSAFE_DEMO_PG_VERSION=%d
export PGSAFE_DEMO_WAL_ARCHIVE=%q
`,
		topo.SuperDSN,
		topo.DSN,
		topo.SSHHost,
		topo.SSHPort,
		topo.SSHUser,
		topo.SSHKeyPath,
		topo.SSHKnownHosts,
		topo.SSHTarget(),
		topo.HostStoragePath,
		topo.ContainerStoragePath,
		remoteBin,
		topo.Version,
		topo.WALArchive,
	)
	if err := os.WriteFile(out, []byte(body), 0o600); err != nil {
		t.Fatalf("write env file: %v", err)
	}
	t.Logf("FIXTURE READY: env file=%s", out)
	t.Logf("  ssh: -p %d -i %s -o UserKnownHostsFile=%s pgsafe@%s",
		topo.SSHPort, topo.SSHKeyPath, topo.SSHKnownHosts, topo.SSHHost)
	t.Logf("  remote pgsafe binary: %s", remoteBin)
	t.Logf("  shared posix root: %s", topo.HostStoragePath)
	t.Logf("  pg super DSN: %s", topo.SuperDSN)

	// Block until the parent process tells us to stop.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Optional max-hold timeout (defense in depth — the test framework's
	// own timeout is usually what catches a runaway).
	hold := 30 * time.Minute
	if s := os.Getenv("PGSAFE_DEMO_HOLD_SECONDS"); s != "" {
		if n, err := strconv.Atoi(s); err == nil && n > 0 {
			hold = time.Duration(n) * time.Second
		}
	}
	select {
	case <-ctx.Done():
	case <-time.After(hold):
	}
	_ = os.Remove(out)
}

func scpUpload(topo *sshtest.Topology, localPath, remotePath string) error {
	args := []string{
		"-P", strconv.Itoa(topo.SSHPort),
		"-i", topo.SSHKeyPath,
		"-o", "UserKnownHostsFile=" + topo.SSHKnownHosts,
		"-o", "StrictHostKeyChecking=yes",
		"-o", "BatchMode=yes",
		localPath,
		topo.SSHTarget() + ":" + remotePath,
	}
	cmd := exec.Command("scp", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("scp %v: %s", err, out)
	}
	return nil
}

func chmodRemote(topo *sshtest.Topology, remotePath, mode string) error {
	args := append([]string{}, topo.SSHExtraArgs()...)
	args = append(args, topo.SSHTarget(), "chmod", mode, remotePath)
	return exec.Command("ssh", args...).Run()
}
